### ISSUE TITLE
Error in paste0("Calibration Evaluation Plot: ", toupper(eval_metric),  :    object 'BaseModelEval' not found 

### ISSUE THREAD

**Issue by larasatiayudia** [AdrianAntico/RemixAutoML#33]
Hi i am trying to compare AutoTS() , AutoCatBoostCARMA() , AutoXGBoostCARMA() , AutoH2oDRFCARMA() , and AutoH2oGBMCARMA() on a single time series. 
AutoTS() , AutoCatBoostCARMA() , AutoXGBoostCARMA() works perfectly fine, but when i tried to run **AutoH2oDRFCARMA** and **AutoH2oGBMCARMA** an error message shown as follow:

**Error in paste0("Calibration Evaluation Plot: ", toupper(eval_metric),  :    object 'BaseModelEval' not found** 

My code run as follow:

result=AutoH2oGBMCARMA(
    x[,1:2],
    TargetColumnName = "POSITIVE_DEMAND",
    DateColumnName = "FULL_DATE",
    FC_Periods = 2,
    TimeUnit = "month",
    TargetTransformation = TRUE,
    Lags =12,
    MA_Periods = 3,
    CalendarVariables = TRUE,
    HolidayVariable = TRUE,
    TimeTrendVariable = TRUE,
    DataTruncate = FALSE,
    #SplitRatios = c(1 - (30+z)/nrow(x), 30/nrow(x), z/nrow(x)),
    EvalMetric = "MAPE",
    GridTune = FALSE,
    ModelCount = 1,
    NTrees = 2000,
    PartitionType = "timeseries",
    MaxMem = "28G",
    NThreads = 8,
    Timer = TRUE)

can AutoH2oDRFCARMA and AutoH2oGBMCARMA applied to a single time series? It those two methods can be applied to a single time series, what is wrong to my code? Hope you help, thanks

**Comment by AdrianAntico** [comment]
@larasatiayudia I'm guessing the issue is the line #SplitRatios is commented out. The function is expecting to partition the data based on those values. Can you run it again without commenting it out to see if that works?

**Comment by larasatiayudia** [comment]
i already comment that out and rerun the code. Unfortunately there is no change, the error still showed up

**Comment by AdrianAntico** [comment]
Can you try running it with TargetTransformation = FALSE

**Comment by larasatiayudia** [comment]
I have tried it and nothing changes, the error message is same

**Comment by AdrianAntico** [comment]
Can you download the package again and try again?

**Comment by larasatiayudia** [comment]
i just did reinstalling as you said by this code:

if ("RemixAutoML" %in% rownames(installed.packages())) { remove.packages("RemixAutoML")}
devtools::install_github('AdrianAntico/RemixAutoML', upgrade = FALSE, dependencies = FALSE, force = TRUE)

i restart the R session too, but still nothing changes. The error message become longer:

Error in paste0("GBM Calibration Evaluation Plot: ", toupper(eval_metric),  : 
  object 'BaseModelEval' not found
In addition: Warning messages:
1: In AutoH2oGBMRegression(data = train, ValidationData = valid, TestData = test,  :
  eval_metric not in MSE, RMSE, MAE, RMSLE
2: In .h2o.startModelJob(algo, params, h2oRestApiVersion) :
 
 Error in paste0("GBM Calibration Evaluation Plot: ", toupper(eval_metric),  : 
  object 'BaseModelEval' not found 

But the point still same

**Comment by AdrianAntico** [comment]
Try the AutoH2oDRFCARMA version

**Comment by AdrianAntico** [comment]
@larasatiayudia This should be fixed now. You'll have to reinstall the package for the changes to take effect. Let me know if you still have trouble.

**Comment by larasatiayudia** [comment]
I tried reinstalling and run it again but the error still showed again. Then i tried changing the EvalMetrics from "MAPE" to "MAE" and it works. My question now is in the time series plot generated, the title showed the number of MAPE but my eval metrics are MAE, is it really the MAPE number or is it actually MAE? And a little bit advise maybe you should remove the "MAPE" option in the documentation about eval metric as it cannot be done, thank you for fast responding

**Comment by AdrianAntico** [comment]
Better yet, why not figure out what the issue is and make a pull request?
